//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Lisimba.Cmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Lisimba.Cmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book name successfully changed..
        /// </summary>
        internal static string AddressBookChangedSuccess {
            get {
                return ResourceManager.GetString("AddressBookChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book was closed..
        /// </summary>
        internal static string AddressBookClosedSuccess {
            get {
                return ResourceManager.GetString("AddressBookClosedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loaded {0} contacts from file &apos;{1}&apos;..
        /// </summary>
        internal static string AddressBookOpenSuccess {
            get {
                return ResourceManager.GetString("AddressBookOpenSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gate is specified for &apos;{0}&apos;. Using default gate &apos;{1}&apos;..
        /// </summary>
        internal static string AddressBookOpenUseDefaultGateWarning {
            get {
                return ResourceManager.GetString("AddressBookOpenUseDefaultGateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book new file name [empty string to cancel]: .
        /// </summary>
        internal static string AskForNewLocation {
            get {
                return ResourceManager.GetString("AskForNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current address book? [y-yes; n-no; c-cancel] .
        /// </summary>
        internal static string AskToSaveAddressBook {
            get {
                return ResourceManager.GetString("AskToSaveAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address Book.
        /// </summary>
        internal static string DefaultAddressBookName {
            get {
                return ResourceManager.GetString("DefaultAddressBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultGate: {0}.
        /// </summary>
        internal static string DefaultGateMessage {
            get {
                return ResourceManager.GetString("DefaultGateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gate was successfully changed..
        /// </summary>
        internal static string GateChangesSuccess {
            get {
                return ResourceManager.GetString("GateChangesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no gate with id = {0}.
        /// </summary>
        internal static string GateNotFoundError {
            get {
                return ResourceManager.GetString("GateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See you soon!.
        /// </summary>
        internal static string GoodByeMessage {
            get {
                return ResourceManager.GetString("GoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update action..
        /// </summary>
        internal static string InvalidUpdateActionError {
            get {
                return ResourceManager.GetString("InvalidUpdateActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisimba ver. {0}.
        /// </summary>
        internal static string LisimbaTitle {
            get {
                return ResourceManager.GetString("LisimbaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New address book successfully created..
        /// </summary>
        internal static string NewAddressBookCreatedSuccess {
            get {
                return ResourceManager.GetString("NewAddressBookCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address book is opened..
        /// </summary>
        internal static string NoAddessBookOpenedError {
            get {
                return ResourceManager.GetString("NoAddessBookOpenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record of an address book being opened. Please specify a file..
        /// </summary>
        internal static string NoAddressBookInConfigFile {
            get {
                return ResourceManager.GetString("NoAddressBookInConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No default gate is set..
        /// </summary>
        internal static string NoDefaultGateError {
            get {
                return ResourceManager.GetString("NoDefaultGateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location has to be specified..
        /// </summary>
        internal static string NoLocationWasSpecifiedError {
            get {
                return ResourceManager.GetString("NoLocationWasSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gate is specified for address book &apos;{0}&apos; and no default gate is set..
        /// </summary>
        internal static string OpenAddressBookNoGateError {
            get {
                return ResourceManager.GetString("OpenAddressBookNoGateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address book was oppened because of unknown error..
        /// </summary>
        internal static string OpenAddressBookUnknownError {
            get {
                return ResourceManager.GetString("OpenAddressBookUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address book was successfully saved..
        /// </summary>
        internal static string SaveAddressBookSuccess {
            get {
                return ResourceManager.GetString("SaveAddressBookSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command.
        /// </summary>
        internal static string UnknownCommandError {
            get {
                return ResourceManager.GetString("UnknownCommandError", resourceCulture);
            }
        }
    }
}
