//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Lisimba.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Lisimba.Wpf.Properties.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Address book is not saved yet &gt;.
        /// </summary>
        internal static string AddressBookNotSavedYet {
            get {
                return ResourceManager.GetString("AddressBookNotSavedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the program..
        /// </summary>
        internal static string ApplicationExitOperationDescription {
            get {
                return ResourceManager.GetString("ApplicationExitOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the currently opened address book..
        /// </summary>
        internal static string CloseCurrentAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("CloseCurrentAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new address book..
        /// </summary>
        internal static string CreateNewAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("CreateNewAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new contact..
        /// </summary>
        internal static string CreateNewContactOperationDescription {
            get {
                return ResourceManager.GetString("CreateNewContactOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string DefaultStatusText {
            get {
                return ResourceManager.GetString("DefaultStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the currently selected contact..
        /// </summary>
        internal static string DeleteCurrentContactOperationDescription {
            get {
                return ResourceManager.GetString("DeleteCurrentContactOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address book is not saved.
        ///Do you wanna save it before proceedeing?.
        /// </summary>
        internal static string EnsureAddressBookIsSaved_Question {
            get {
                return ResourceManager.GetString("EnsureAddressBookIsSaved_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string EnsureAddressBookIsSaved_Title {
            get {
                return ResourceManager.GetString("EnsureAddressBookIsSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorPopup_Title {
            get {
                return ResourceManager.GetString("ErrorPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the current address book..
        /// </summary>
        internal static string ExportOperationDescription {
            get {
                return ResourceManager.GetString("ExportOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoPopup_Title {
            get {
                return ResourceManager.GetString("InfoPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address book is opened..
        /// </summary>
        internal static string NoAddessBookOpenedError {
            get {
                return ResourceManager.GetString("NoAddessBookOpenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open address book from file..
        /// </summary>
        internal static string OpenAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("OpenAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports an address book..
        /// </summary>
        internal static string OpenFromOperationDescription {
            get {
                return ResourceManager.GetString("OpenFromOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes again the last action that was undone..
        /// </summary>
        internal static string RedoOperationDescription {
            get {
                return ResourceManager.GetString("RedoOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current opened address book..
        /// </summary>
        internal static string SaveAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("SaveAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current opened address book with another name..
        /// </summary>
        internal static string SaveAsAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("SaveAsAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays info about Lisimba..
        /// </summary>
        internal static string ShowAboutOperationDescription {
            get {
                return ResourceManager.GetString("ShowAboutOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the address book properties..
        /// </summary>
        internal static string ShowAddressBookPropertiesOperationDescription {
            get {
                return ResourceManager.GetString("ShowAddressBookPropertiesOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the last executed action..
        /// </summary>
        internal static string UndoOperationDescription {
            get {
                return ResourceManager.GetString("UndoOperationDescription", resourceCulture);
            }
        }
    }
}
