//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lindani {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Lindani : global::System.Configuration.ApplicationSettingsBase {
        
        private static Lindani defaultInstance = ((Lindani)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Lindani())));
        
        public static Lindani Default {
            get {
                return defaultInstance;
            }
        }
    }
}
