//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Lisimba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZodiacResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZodiacResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Lisimba.Properties.ZodiacResources", typeof(ZodiacResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        internal static string ZodiacSign_Aquarius {
            get {
                return ResourceManager.GetString("ZodiacSign_Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        internal static string ZodiacSign_Aries {
            get {
                return ResourceManager.GetString("ZodiacSign_Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        internal static string ZodiacSign_Cancer {
            get {
                return ResourceManager.GetString("ZodiacSign_Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorn.
        /// </summary>
        internal static string ZodiacSign_Capricorn {
            get {
                return ResourceManager.GetString("ZodiacSign_Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        internal static string ZodiacSign_Gemini {
            get {
                return ResourceManager.GetString("ZodiacSign_Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        internal static string ZodiacSign_Leo {
            get {
                return ResourceManager.GetString("ZodiacSign_Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        internal static string ZodiacSign_Libra {
            get {
                return ResourceManager.GetString("ZodiacSign_Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        internal static string ZodiacSign_Pisces {
            get {
                return ResourceManager.GetString("ZodiacSign_Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        internal static string ZodiacSign_Sagittarius {
            get {
                return ResourceManager.GetString("ZodiacSign_Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpio.
        /// </summary>
        internal static string ZodiacSign_Scorpio {
            get {
                return ResourceManager.GetString("ZodiacSign_Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        internal static string ZodiacSign_Taurus {
            get {
                return ResourceManager.GetString("ZodiacSign_Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        internal static string ZodiacSign_Virgo {
            get {
                return ResourceManager.GetString("ZodiacSign_Virgo", resourceCulture);
            }
        }
    }
}
