//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DustInTheWind.Lisimba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DustInTheWind.Lisimba.Properties.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the program..
        /// </summary>
        internal static string ApplicationExitOperationDescription {
            get {
                return ResourceManager.GetString("ApplicationExitOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the currently opened address book..
        /// </summary>
        internal static string CloseCurrentAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("CloseCurrentAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wanna delete the contact {0} ?.
        /// </summary>
        internal static string ContactDelete_ConfirametionQuestion {
            get {
                return ResourceManager.GetString("ContactDelete_ConfirametionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContactDelete_ConfirmationTitle {
            get {
                return ResourceManager.GetString("ContactDelete_ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new address book..
        /// </summary>
        internal static string CreateNewAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("CreateNewAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new contact..
        /// </summary>
        internal static string CreateNewContactOperationDescription {
            get {
                return ResourceManager.GetString("CreateNewContactOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address Book.
        /// </summary>
        internal static string DefaultAddressBookName {
            get {
                return ResourceManager.GetString("DefaultAddressBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string DefaultStatusText {
            get {
                return ResourceManager.GetString("DefaultStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the currently selected contact..
        /// </summary>
        internal static string DeleteCurrentContactOperationDescription {
            get {
                return ResourceManager.GetString("DeleteCurrentContactOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current address book is not saved.
        ///Do you wanna save it before proceedeing?.
        /// </summary>
        internal static string EnsureAddressBookIsSaved_Question {
            get {
                return ResourceManager.GetString("EnsureAddressBookIsSaved_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string EnsureAddressBookIsSaved_Title {
            get {
                return ResourceManager.GetString("EnsureAddressBookIsSaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current opened address book in Yahoo! csv format..
        /// </summary>
        internal static string ExportYahooCsvOperationDescription {
            get {
                return ResourceManager.GetString("ExportYahooCsvOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no gate with id = {0}.
        /// </summary>
        internal static string GateNotFoundError {
            get {
                return ResourceManager.GetString("GateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import address book from Yahoo! csv format..
        /// </summary>
        internal static string ImportYahooCsvOperationDescription {
            get {
                return ResourceManager.GetString("ImportYahooCsvOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address book is opened..
        /// </summary>
        internal static string NoAddessBookOpenedError {
            get {
                return ResourceManager.GetString("NoAddessBookOpenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gate is associated with the address book..
        /// </summary>
        internal static string NoGateWasSpecifiedError {
            get {
                return ResourceManager.GetString("NoGateWasSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A location has to be specified..
        /// </summary>
        internal static string NoLocationWasSpecifiedError {
            get {
                return ResourceManager.GetString("NoLocationWasSpecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open address book from file..
        /// </summary>
        internal static string OpenAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("OpenAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current opened address book..
        /// </summary>
        internal static string SaveAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("SaveAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current opened address book with another name..
        /// </summary>
        internal static string SaveAsAddressBookOperationDescription {
            get {
                return ResourceManager.GetString("SaveAsAddressBookOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays info about Lisimba..
        /// </summary>
        internal static string ShowAboutOperationDescription {
            get {
                return ResourceManager.GetString("ShowAboutOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the address book properties..
        /// </summary>
        internal static string ShowAddressBookPropertiesOperationDescription {
            get {
                return ResourceManager.GetString("ShowAddressBookPropertiesOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        internal static string ZodiacSign_Aquarius {
            get {
                return ResourceManager.GetString("ZodiacSign_Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        internal static string ZodiacSign_Aries {
            get {
                return ResourceManager.GetString("ZodiacSign_Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        internal static string ZodiacSign_Cancer {
            get {
                return ResourceManager.GetString("ZodiacSign_Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorn.
        /// </summary>
        internal static string ZodiacSign_Capricorn {
            get {
                return ResourceManager.GetString("ZodiacSign_Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        internal static string ZodiacSign_Gemini {
            get {
                return ResourceManager.GetString("ZodiacSign_Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        internal static string ZodiacSign_Leo {
            get {
                return ResourceManager.GetString("ZodiacSign_Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        internal static string ZodiacSign_Libra {
            get {
                return ResourceManager.GetString("ZodiacSign_Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        internal static string ZodiacSign_Pisces {
            get {
                return ResourceManager.GetString("ZodiacSign_Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        internal static string ZodiacSign_Sagittarius {
            get {
                return ResourceManager.GetString("ZodiacSign_Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpio.
        /// </summary>
        internal static string ZodiacSign_Scorpio {
            get {
                return ResourceManager.GetString("ZodiacSign_Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        internal static string ZodiacSign_Taurus {
            get {
                return ResourceManager.GetString("ZodiacSign_Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        internal static string ZodiacSign_Virgo {
            get {
                return ResourceManager.GetString("ZodiacSign_Virgo", resourceCulture);
            }
        }
    }
}
